### ISSUE TITLE
ES6 Class Support

### ISSUE THREAD

**Issue by chrishoage** [jacobp100/state-transitions#1]
This looks pretty awesome, do you plan to support [ES6 Classes](http://facebook.github.io/react/blog/2015/01/27/react-v0.13.0-beta-1.html)? Perhaps though [composition](https://medium.com/@dan_abramov/mixins-are-dead-long-live-higher-order-components-94a0d2f9e750)? (Composition would have the added benefit of supporting [ES7 Decorators](https://github.com/wycats/javascript-decorators))

**Comment by jacobp100** [comment]
Are you looking for something like this?

``` js
const ListView = animateElement([TransitionInOut],
    class ListView extends React.Component {
        render() {
            …
        }
    }
);
```

**Comment by jacobp100** [comment]
Done some work over on https://github.com/jacobp100/state-transitions/tree/es6-classes (see the demo for how to implement). Would be nice to get some feedback!

**Comment by chrishoage** [comment]
This is pretty good, might I suggest returning a new function to wrap the component to better support decorators

Using babel + decorators it would look something like this: 

``` js
@animateComponent({
    tweenState: {},
    transitionInOut: {
        animateOutClassName: 'link-view--leaving'
    }
})
class ListView extends Component {

}
```

And with out decorators

``` js
class ListView extends Component {

}

const animateSettings = {
    tweenState: {},
    transitionInOut: {
        animateOutClassName: 'link-view--leaving'
    }
}

export default animateComponent(animateSettings)(ListView)
```

While composing the component with a "classic" component will work well for the short term, it appears that React may not support mixins forever, and is considering deprecating them at some point (and based on how Relay works it looks like composition might be that answer to mixins). If you need ideas on how to work with refs with out mixins take a look at [ReactDnD](http://gaearon.github.io/react-dnd/) it has a pretty solid API that works great with "classic" components and es6 ones.

**Comment by jacobp100** [comment]
Just pushed a commit to allow decorators as you said.

I’m aware they won’t support mixins forever. I figure when they do, it’s only going to be a few lines of code to add the lifecycle handlers—basically manually doing what mixins are currently doing.

Thinking about it, I suppose this whole API could be done via regular components, which would make this whole topic moot.

``` js
<TweenState id=‘test’ duration=0.6>
    …
</TweenState>
```

**Comment by chrishoage** [comment]
If you can make the lib work with a declarative API that would be the most "react like". I have not delved very deeply into the source so I have no idea if it would offer the level of control you need, but if it does that would be awesome. 

From what I have been reading from the react devs about ES6 and mixins I wouldn't be so sure it will be a "few lines of code" change, but nobody truly knows at this point in time.

**Comment by jacobp100** [comment]
Thanks for the feedback. Managed to get the API as described before—I think it’s a lot better than before.

I believe this completely solves this issue, so I’m going to close it, but feel free to reopen if you wish to add anything else to the discussion!
